# Generated by Django 4.0.3 on 2022-03-02 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('affiliation', models.CharField(max_length=100, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('filename', models.CharField(max_length=100, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('agency', models.CharField(max_length=100)),
                ('deadline', models.DateField(null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('url', models.URLField(null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroundSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pi', models.CharField(max_length=40)),
                ('tel_diameter', models.DecimalField(decimal_places=1, max_digits=5)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('deadline', models.DateField(null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('url', models.URLField(null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('abstract_deadline', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, max_length=500, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('filename', models.CharField(max_length=100, null=True)),
                ('caption', models.CharField(max_length=500, null=True)),
                ('credit', models.CharField(max_length=50, null=True)),
                ('url', models.URLField(null=True)),
                ('thumbnail', models.CharField(max_length=100, null=True)),
                ('keywords', models.CharField(max_length=200, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('group', models.CharField(max_length=100)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('filename', models.CharField(max_length=100, null=True)),
                ('caption', models.CharField(max_length=500, null=True)),
                ('credit', models.CharField(max_length=50, null=True)),
                ('url', models.URLField(null=True)),
                ('thumbnail', models.CharField(max_length=100, null=True)),
                ('keywords', models.CharField(max_length=200, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('journal', models.CharField(max_length=50, null=True)),
                ('volume', models.CharField(max_length=10, null=True)),
                ('page', models.CharField(max_length=10, null=True)),
                ('url', models.URLField(null=True)),
                ('search_key', models.CharField(max_length=200)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutorialPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_title', models.CharField(max_length=20, null=True)),
                ('course_index', models.IntegerField(null=True)),
                ('text', models.TextField()),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.author')),
                ('references', models.ManyToManyField(to='website.reference')),
            ],
        ),
        migrations.CreateModel(
            name='InteractiveTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('tools_index', models.IntegerField(null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.author')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_title', models.CharField(max_length=20, null=True)),
                ('course_index', models.IntegerField(null=True)),
                ('text', models.TextField()),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.author')),
            ],
        ),
    ]
