# Generated by Django 4.0.3 on 2022-03-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_interactivetool_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='affiliation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
