# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='caption',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='caption',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
