# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_auto_20170112_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
