# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_auto_20160809_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
