# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-03 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_sitepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
