# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_auto_20170112_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactivetool',
            name='title',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
