# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-03 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_interactivetool'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactivetool',
            name='text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
