# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-03 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0005_interactivetool_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactivetool',
            name='tools_index',
            field=models.IntegerField(null=True),
        ),
    ]
