# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0006_grant_job_meeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='date',
            new_name='date_start',
        ),
        migrations.AddField(
            model_name='meeting',
            name='date_end',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
