# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-03 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0007_conceptpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pi', models.CharField(max_length=40)),
                ('tel_diameter', models.DecimalField(decimal_places=1, max_digits=5)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
