# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0007_auto_20170120_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='keywords',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='keywords',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='thumbnail',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
