# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0008_auto_20170302_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='caption',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='caption',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
