# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-03 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0008_groundsurvey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('affiliation', models.CharField(max_length=100)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='conceptpage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tutorialpage',
            name='author',
        ),
    ]
