# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-03 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0009_auto_20161103_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptpage',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='affiliation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
