# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0009_auto_20170302_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='abstract_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='topic',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
