# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-05 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0010_auto_20170616_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('filename', models.CharField(max_length=100, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
