# Generated by Django 3.0.3 on 2020-06-10 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0011_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptpage',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='sitepage',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='tutorialpage',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='conceptpage',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutorial.Author'),
        ),
        migrations.AlterField(
            model_name='interactivetool',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutorial.Author'),
        ),
        migrations.AlterField(
            model_name='tutorialpage',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutorial.Author'),
        ),
    ]
