# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0011_tutorialpage_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('link_group', models.CharField(max_length=100)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_author', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('journal', models.CharField(max_length=50)),
                ('volume', models.CharField(max_length=10)),
                ('page', models.CharField(max_length=10)),
                ('arxiv', models.CharField(max_length=20)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
