# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0012_onlineresource_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='arxiv',
        ),
        migrations.AddField(
            model_name='reference',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='journal',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='page',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='volume',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
