# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0013_auto_20161111_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='lead_author',
            new_name='authors',
        ),
    ]
