# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0014_auto_20161111_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialpage',
            name='references',
            field=models.ManyToManyField(to='tutorial.Reference'),
        ),
    ]
